# A YAML confihuration file that the service might use...
#
# THIS IS JUST AN EXAMPLE THAT THE TEMPLATE PROVIDES TO SHOW CONFIG FILE HANDLING.

# The ``redis.clusters`` setting is used, unsurprisingly, to configure Redis
# clusters. These clusters can be then referred to by name when configuring
# backends such as the cache.
redis.clusters:
  default:
    hosts:
      0:
        host: 127.0.0.1
        port: 6379

# Uploaded media uses these `filestore` settings.
filestore:
  backend: 'filesystem'
  options:
    location: '/var/opt/jupyterhub'
